<?php
header("Content-type: text/plain");

/*
=========================================
CONFIGURATION
=========================================
*/
// Post author ID
$config__author_id = 1;
// Name of the file generated by the Twitter Archive
$config__path_archive = dirname(__FILE__) . '/tweet.js';
$config__path_import = dirname(__FILE__) . '/../wp-admin/includes/import.php';
$config__path_admin = dirname(__FILE__) . '//../wp-admin/includes/admin.php';
$config__post_title = "Tweet";
// When creating the actual query
$config__post_type = "post";
// Your twitter username
$config__twitter_user = "ricard_dev";
// Where is the WP Load located
$config__wpload_path = "../wp-load.php";

/*
=========================================
STOP RIGHT HERE
=========================================
(Unless you know what you're doing)
*/
// We are in a subfolder
include_once($config__wpload_path);
require_once $config__path_import;
require_once $config__path_admin;

function parse_files() {
	global $wp_filesystem,
				$wpdb,
				$config__author_id,
				$config__category_id,
				$config__path_archive,
				$config__post_title,
				$config__post_type,
				$config__twitter_user;

	WP_Filesystem();

	$tweets = array();

	$tweet_json = file_get_contents( $config__path_archive );
	$tweet_json = preg_replace( '/^[^\[]*/', '', $tweet_json );
	$tweets = json_decode( $tweet_json );

	if ( is_array( $tweets ) ) {
		$number_of_tweets = count($tweets);

		echo "INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES";

		for ($i = 0; $i < $number_of_tweets; $i++) {
			$tweet = $tweets[$i];

			// Parse/adjust dates
			$post_date_gmt = strtotime( $tweet->created_at );
			$post_date_gmt = gmdate( 'Y-m-d H:i:s', $post_date_gmt );
			$post_date     = get_date_from_gmt( $post_date_gmt );

			/*
				Add the URL to the tweet
				Hardcode my twitter handle, Twitter will redirect to the
				Correct user if the status ID does not match the user.
			*/
			$tweet_url = " \n\n" . "https://twitter.com/" . $config__twitter_user . "/status/" . $tweet->id_str;

			$post_content = make_clickable(trim($tweet->full_text));

			// Clean up content a bit
			$post_content = $wpdb->escape( html_entity_decode( trim( $post_content) ) );
			// Handle entities supplied by Twitter
			if ( count( $tweet->entities->urls ) ) {
				foreach ( $tweet->entities->urls as $url )
					$post_content = str_replace( $url->url, $url->expanded_url, $post_content );
			}

			// We don't want to make the tweet url clicable or the oembed won't wok
			$post_content .= $tweet_url;

			// For each insert in the query
			if ($i !== 0 && $i < $number_of_tweets) {
				echo ",";
			}

			echo "(NULL, '1', '" . $post_date . "', '" . $post_date_gmt . "', '" . $post_content . "', 'Tweet', '', 'publish', 'open', 'open', '', 'tweet-" . $tweet->id_str . "', '', '', '" . $post_date . "', '" . $post_date_gmt . "', '', '0', '/tweet-" . $tweet->id_str . "/', '0', 'post', '', '0')";

		} // if we tweets is an array
	} // End of for loop
} // End of the parse_files()

parse_files();